Try fix workflow failure

diff --git a/.github/workflows/node.js.yml b/.github/workflows/node.js.yml
--- a/.github/workflows/node.js.yml
+++ b/.github/workflows/node.js.yml
@@ -15,7 +15,7 @@ jobs:
 
     strategy:
       matrix:
-        node-version: [21.x] 
+        node-version: [21.x]
         # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
 
     steps:
@@ -24,11 +24,18 @@ jobs:
         with:
           node-version: ${{ matrix.node-version }}
           cache: 'npm'
-
       - name: Checkout repository
         uses: actions/checkout@v4
+      - name: Check for lock file
+        run: |
+          if [ -f package-lock.json ]; then
+            echo "Lock file exists."
+          else
+            echo "Error: Dependencies lock file not found."
+            exit 1
+          fi
       - name: Install dependencies
-        run: npm ci
+        run: npm ci --if-present || npm install
       - name: Build
         run: npm run build --if-present
       - name: Test
